% Made advisory system for Btech level stream selection based on some
% question asked to students/users. System will recommend the best
% suitable stream for user based on user_responses.For running this
% program simply consult the file in prolog and then type systems.

% starting of program
% it will calls different function and determine the suitable stream based on the user response and
% also suggest some career path user can take after completion of the particular stream/course.

systems :-
  %this file is generated by the python code and it contains facts about the user interest.
  consult("C:/Users/Sakshi/Desktop/AI/Assignment5/AI-A5-Sakshi_Kumari-MT21141/Afacts.txt"),
  start,
  find_stream(Stream).

start :-
  write('In which stream sholud I pursue in my B.Tech?'), nl.

% function for finding the suitable stream for student when he respond to some questions asked
find_stream(Stream) :-
  stream(Stream), !.

%btech_streams
% Btech_stream finding, it will asks some question to you and give the suitable response according to your answer
% function called for different program like cse,it,ece,me etc.

stream(computer_science) :-
  computer_systems(yes),
  computer_or_manually(computer),
  (better_in_solving_problem(solving_problem)),
  work_with_numbers(yes),
  (technology(develop);technology(apply)),
  maths(yes),
  deal_with_circuits(no),
  (chemistry(yes);chemistry(no)),
  (physics(yes);physics(no)),
  (biology(yes);biology(no)),
  write('Recommendation: Computer Science '),nl,
  write('After completion of recommended stream you can choose below career path:'),nl,
  write('- Software Engineer'),nl,
  write('- System Engineer'),nl,
  write('- App Developer'),nl,
  write('- Game Developer'),nl,
  write('- Network Specialist'),nl,
  write('- Researcher'),nl,
  write('- Software Quality Assurance Engineer'),nl.

stream(information_technology) :-
  computer_systems(yes),
  computer_or_manually(computer),
  (better_in_solving_problem(solved_problem_as_application)),
  (work_with_numbers(yes);work_with_numbers(no)),
  technology(apply),
  maths(yes),
  deal_with_circuits(no),
  (chemistry(yes);chemistry(no)),
  (physics(yes);physics(no)),
  (biology(yes);biology(no)),
  write('Recommendation: Information Technology '),nl,
  write('After completion of recommended stream you can choose below career path:'),nl,
 write('- Network Administrator'),nl,
  write('- Computer Support Specialist'),nl,
  write('- Information Technology Manager'),nl,
  write('- Database Administrator'),nl,
  write('- System Administrator'),nl,
  write('- Information Systems Manager.'),nl.

stream(electronic_engineering) :-
  computer_systems(no),
  computer_or_manually(manually),
  better_in_solving_problem(solving_problem),
  (work_with_numbers(yes);work_with_numbers(no)),
  technology(apply),
  maths(yes),
  deal_with_circuits(yes),
  (chemistry(yes);chemistry(no)),
  (physics(yes);physics(no)),
  (biology(yes);biology(no)),
  write('Recommendation: Electrical/Electronic Engineering '),
  nl,
  write('After completion of recommended stream you can choose below career path:'),nl,
  write('- Electrical or Electronic Engineer'),nl,
  write('- Technical Director'),nl,
  write('- Network Planning Engineer'),
  write('- Desktop Support Engineer'),nl,
  write('- Electronics Device and Development Engineer').

stream(mechanical_engineering) :-
  computer_systems(no),
  computer_or_manually(manually),
  better_in_solving_problem(solved_problem_as_application),
  work_with_numbers(yes),
  technology(apply),
  maths(yes),
  deal_with_circuits(no),
  (chemistry(yes);chemistry(no)),
  (physics(yes)),
  (biology(yes);biology(no)),
  write('Recommendation: Mechanical Engineering '),
  nl,
  write('After completion of recommended stream you can choose below career path:'),nl,
  write('- Mechanical Engineer'),nl,
  write('- Production Engineer'),nl,
  write('- Failure Analyst Engineer'),nl,
  write('- M&E Engineer'),nl,
  write('- QC Engineer'),nl,
  write('- Manufacturing Engineer'),nl,
  write('- R&D Engineer'),nl,
  write('- Design Engineer'),nl,
  write('- Product Engineer').

stream(chemical_engineering) :-
  computer_systems(no),
  computer_or_manually(manually),
  better_in_solving_problem(solved_problem_as_application),
  work_with_numbers(no),
  technology(apply),
  (maths(yes);maths(no)),
  deal_with_circuits(no),
  chemistry(yes),
  (physics(yes);physics(no)),
  (biology(yes);biology(no)),
  write('Recommendation: Chemical Engineering '),
  nl,
  write('After completion of recommended stream you can choose below career path:'),nl,
  write('- Process Engineer'),nl,
  write('- Quality Assurance Engineer'),nl,
  write('- Chemical & Biochemical Engineer'),nl,
  write('- Contamination Engineer').

stream(biotechnology) :-
  computer_systems(no),
  computer_or_manually(manually),
  better_in_solving_problem(solved_problem_as_application),
  work_with_numbers(no),
  technology(apply),
  biology(yes),
  chemistry(yes),
  (maths(yes);maths(no)),
  (physics(yes);physics(no)),
  write('Recommendation: Biotechnology '),
  nl,
  write('After completion of recommended stream you can choose below career path:'),nl,
  write('- Pharmaceutical Research & Development'),nl,
  write('- Pharmaceutical Marketing Director'),nl,
  write('- Clinical Trial Manager'),nl,
  write('- Clinical Research Scientist'),nl,
  write('- Biomedical & Biotechnology Research Scientist'),nl,
  write('- Medical & Scientific Product Specialist'),nl,
  write('- Medical Laboratories Director'),nl,
  write('- Academia (Science Educator)').

stream(_):- write("Sorry no suitable Stream found").



